chatApp/urls.py
from django.urls import path
from chatApp import views

urlpatterns = [

]

productionsApp/api/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from productionsApp.api import views

router = DefaultRouter()
router.register('product-ratings', views.ProductRatingsVS, basename='product-ratings')

urlpatterns = [
    path('', include(router.urls)),
    # Products' Links
    path('products/', views.ProductsVS.as_view(), name='all-production'),
    path('products/gallery/', views.ProductGalleryGL.as_view(), name='product-galleries'),
    path('products/<int:pk>', views.ProductDetailsVS.as_view(), name='brand-detail'),
    path('product-list/', views.ProductList.as_view(), name='product-list-by-price'),
    # Brands' Links
    path('brands/', views.BrandsVS.as_view(), name='all-brands'),
    path('brands/<int:pk>', views.BrandDetailsVS.as_view(), name='brand-detail'),
    path('brands/<brand>', views.BrandFilteringGA.as_view(), name='product-list-by-brand'),
    # Categories' Links
    path('category/', views.CategoryFilteringGA.as_view(), name='product-list-by-brand'),
    # Tags' Links
    path('tag/', views.ProductsTagsVS.as_view(), name='all-tags'),
    path('tag/<int:pk>/',views.ProductsTagDetailsVS.as_view(), name='all-tags'),
    # Product Comments
    path('<int:id>/product-comments/', views.ProductCommentsGV.as_view(), name='product-comments'),
    path('<int:id>/product-comments/<int:pk>/', views.ProductCommentGR.as_view(), name='product-comment'),
    path('<int:id>/product-comments/create/', views.CreateProductCommentGC.as_view(), name='product-comments-create'),
    path('<int:id>/product-comments/change/<int:pk>/', views.ChangeProductCommentGRUD.as_view(),
         name='product-comments-change'),
    # Brand Comments
    path('<int:id>/brand-comments/', views.BrandCommentsGL.as_view(), name='brand-comments'),
    path('<int:id>/brand-comments/<int:pk>/', views.BrandCommentGR.as_view(), name='brand-comment'),
    path('<int:id>/brand-comments/create/', views.CreateBrandCommentGC.as_view(), name='brand-comments-create'),
    path('<int:id>/brand-comments/change/<int:pk>/', views.ChangeBrandCommentGRUD.as_view(),
         name='brand-comments-change'),
]

productionsApp/urls.py
from django.urls import path
from productionsApp import views

urlpatterns = [
    path('', views.AllProductionsView.as_view(), name='all-productions-page'),
    path('add-product-comment/', views.addProductComment, name='product-comment-page'),
    path('add-brand-comment/', views.addBrandComment, name='brand-comment-page'),
    path('brands/', views.BrandsListView.as_view(), name='brands-page'),
    path('brands/<brand>', views.AllProductionsView.as_view(), name='product-list-by-brand'),
    path('category/<cat>', views.AllProductionsView.as_view(), name='product-list-by-category'),
    path('brands/<pk>/', views.BrandDetailView.as_view(), name='brand-detail-page'),
    path('<slug:slug>/', views.ProductionsDetailView.as_view(), name='detail-productions-page'),
]

shopCenter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # URLs
    path('', include('homeApp.urls')),
    path('', include('contactApp.urls')),
    path('', include('userAccountApp.urls')),
    path('userpanel/', include('userPanelApp.urls')),
    path('order/', include('orderApp.urls')),
    path('productions/', include('productionsApp.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),

    # API URLs Version 1
    path('api/v1/', include('homeApp.api.urls')),
    path('api/v1/', include('contactApp.api.urls')),
    path('api/v1/', include('userAccountApp.api.urls')),
    path('api/v1/userpanel/', include('userPanelApp.api.urls')),
    path('api/v1/order/', include('orderApp.api.urls')),
    path('api/v1/productions/', include('productionsApp.api.urls')),
    path('api/v1/ratings/', include('star_ratings.urls', namespace='ratings')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productionsApp/models.py
from django.db import models
from django.shortcuts import reverse
from jalali_date import datetime2jalali, date2jalali
from shopCenter import settings


# Brand Model for Products
class ProductsBrand(models.Model):
    title = models.CharField(max_length=200, db_index=True, verbose_name='نام برند')
    titleEN = models.CharField(max_length=300, db_index=True, verbose_name='نام انگلیسی برند', null=True)
    isActive = models.BooleanField(verbose_name='فعال / غیرفعال')
    image = models.ImageField(upload_to='brands/', null=True, blank=True, verbose_name='تصویر محصول')
    shortDescription = models.TextField(verbose_name='توضیحات کوتاه', null=True)
    description = models.TextField(verbose_name='توضیحات برند', null=True)
    createDate = models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ نوشته')
    haveComments = models.BooleanField(null=True, blank=True, verbose_name='نمایش نظرات')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'برند'
        verbose_name_plural = 'برند ها'

    def createJalalidate(self):
        date = date2jalali(self.createDate).strftime('14%y/%m/%d')
        return date

    def createJalalitime(self):
        time = datetime2jalali(self.createDate).strftime('%H : %M')
        return time


# Comment Model for Brand
class BrandsComments(models.Model):
    isActive = models.BooleanField(verbose_name='نمایش نظر', null=True)
    brand = models.ForeignKey(ProductsBrand, on_delete=models.CASCADE, verbose_name='نام برند')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='نام کاربر')
    parent = models.ForeignKey('BrandsComments', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    createDate = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')
    message = models.TextField(verbose_name='متن نظر')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'نظر درباره برند'
        verbose_name_plural = 'نظرات برند'

    def createJalalidate(self):
        date = date2jalali(self.createDate).strftime('14%y/%m/%d')
        return date

    def createJalalitime(self):
        time = datetime2jalali(self.createDate).strftime('%H:%M')
        return time


# Category Model for Products
class ProductsCategory(models.Model):
    title = models.CharField(max_length=300, db_index=True, verbose_name='عنوان دسته بندی')
    urlTitle = models.CharField(max_length=300, db_index=True, verbose_name='Url عنوان در')
    image = models.ImageField(upload_to='images/category', null=True, blank=True, verbose_name='تصویر دسته بندی')
    isActive = models.BooleanField(verbose_name='فعال / غیرفعال')
    isDelete = models.BooleanField(verbose_name='حذف شده / نشده', null=True)
    parent = models.ForeignKey('CategoryParent', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='دسته بندی والد')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی محصول'
        verbose_name_plural = 'دسته بندی  های محصولات'


# Parent Model for Category
class CategoryParent(models.Model):
    title = models.CharField(max_length=300, db_index=True, verbose_name='نام')
    titleEN = models.CharField(max_length=300, db_index=True, verbose_name='نام انگلیسی', null=True)
    isActive = models.BooleanField(verbose_name='فعال / غیرفعال')

    class Meta:
        verbose_name = 'دسته بندی والد'
        verbose_name_plural = 'دسته بندی های والد'

    def __str__(self):
        return self.title


# Product Model
class Products(models.Model):
    title = models.CharField(max_length=300, verbose_name='نام محصول')
    category = models.ManyToManyField(ProductsCategory, related_name='productCategories',
                                      verbose_name='دسته بندی محصول')
    image = models.ImageField(upload_to='products/', null=True, blank=True, verbose_name='تصویر محصول')
    brand = models.ForeignKey(ProductsBrand, on_delete=models.CASCADE, verbose_name='برند', null=True, blank=True)
    price = models.IntegerField(verbose_name='قیمت')
    productCount = models.IntegerField(verbose_name='تعداد محصول', default=0)
    dateOfCreate = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='تاریخ ثبت')
    shortDescription = models.CharField(max_length=360, db_index=True, default='empty', verbose_name='توضیحات کوتاه')
    Description = models.TextField(db_index=True, verbose_name='توضیحات اصلی')
    isActive = models.BooleanField(default=False, verbose_name='فعال /غیر فعال')
    slug = models.SlugField(default="", null=False, db_index=True, blank=True, max_length=200, unique=True,
                            verbose_name='عنوان در url')
    isDelete = models.BooleanField(verbose_name='حذف شده / نشده')
    haveComments = models.BooleanField(null=True, blank=True, verbose_name='نمایش نظرات')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def get_absolute_url(self):
        return reverse('product-details-page', args=[self.slug])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


# Gallery Model for Products
class ProductGallery(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول',
                                related_name='product_gallery')
    image = models.ImageField(upload_to='images/productGallery', verbose_name='تصویر')

    class Meta:
        verbose_name = 'تصویر محصول'
        verbose_name_plural = 'تصاویر محصولات'

    def __str__(self):
        return self.product.title


# Comment Model for Products
class ProductsComments(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول')
    parent = models.ForeignKey('ProductsComments', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='کاربر', )
    createDate = models.DateTimeField(verbose_name='تاریخ ثبت', auto_now_add=True)
    message = models.TextField(verbose_name='متن نظر')

    class Meta:
        verbose_name = 'نظر درباره محصول'
        verbose_name_plural = 'نظرات محصولات'

    def createJalalidate(self):
        date = date2jalali(self.createDate).strftime('14%y/%m/%d')
        return date

    def createJalalitime(self):
        time = datetime2jalali(self.createDate).strftime('%H:%M')
        return time

    def __str__(self):
        return str(self.user)


# Tag Model for Products
class ProductsTags(models.Model):
    caption = models.CharField(max_length=300, db_index=True, verbose_name='تگ محصول')
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product_tags')

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = 'تگ محصول'
        verbose_name_plural = 'تگ های محصولات'


# Visit Model for Products
class ProductsVisit(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول', related_name='productsvisit')
    ip = models.CharField(max_length=30, verbose_name='آی پی کاربر')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='کاربر', null=True, blank=True,
                             on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product.title} / {self.ip}'

    class Meta:
        verbose_name = 'بازید محصول'
        verbose_name_plural = 'بازید های محصول'


# Rating Model for Products
class ProductsRating(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول')
    rating = models.IntegerField(verbose_name='امتیاز', null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='کاربر')
    isRating = models.BooleanField(verbose_name='نظر داده / نداده')

    class Meta:
        verbose_name = 'امتیاز محصول'
        verbose_name_plural = 'امتبازات محصولات'

    def __str__(self):
        return str(self.product)

productionsApp/templates/productionsApp/brandDetail.html
{% extends 'shared/master.html' %}
{% load render_partial %}
{% load static %}
{% load ratings %}
{% block title %}{{ productsbrand.titleEN }}{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-3 text-warning" style="font-size:large">
                {% ratings object %}
                </div>
                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">{{ productsbrand.titleEN }}</h2>
                        <div class="single-blog-post">
                            <h3>{{ productsbrand.title }}</h3>
                            <div class="post-meta">
                                <ul>
                                    <li><i class="fa fa-user"></i>کاربر مدیر</li>
                                    <li><i class="fa fa-clock-o"></i>{{ productsbrand.createJalalitime }}</li>
                                    <li><i class="fa fa-calendar"></i>{{ productsbrand.createJalalidate }}</li>
                                </ul>
                            </div>
                            <a href="">
                                <img src="{{ productsbrand.image.url }}" alt="{{ productsbrand.titleEN }}">
                            </a>
                            <p>{{ productsbrand.shortDescription }}</p>
                            <p>{{ productsbrand.description }}</p>
                        </div>
                    </div>
                    {% if productsbrand.haveComments %}

                        <!--Comments-->

                        <div class="response-area" id="comments_area">
                            <h2> نظرات ({{ comments_count }})</h2>
                            <ul class="media-list">
                                {% for comment in comments %}
                                    <li class="media" id="single_comment_box_{{ comment.id }}">
                                        <a class="pull-right" href="#">
                                            <img class="media-object" src="/static/images/blog/user.png" alt="">
                                        </a>
                                        <div class="media-body">
                                            <ul class="sinlge-post-meta">
                                                <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                                                <li><i class="fa fa-clock-o"></i> {{ comment.createJalalitime }}</li>
                                                <li>
                                                    <i class="fa fa-calendar"></i> {{ comment.createJalalidate }}
                                                </li>
                                            </ul>
                                            <p>
                                                {{ comment.message }}
                                            </p>
                                            <a class="btn btn-primary" onclick="fillBrandParentId({{ comment.id }})"><i
                                                    class="fa fa-reply"></i>پاسـخ</a>
                                        </div>
                                    </li>

                                    {% for sub_comment in comment.brandscomments_set.all %}
                                        <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                                            <a class="pull-right" href="#">
                                                <img class="media-object" src="/static/images/blog/user_response.png" alt="">
                                            </a>
                                            <div class="media-body">
                                                <ul class="sinlge-post-meta">
                                                    <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                                                    <li><i class="fa fa-clock-o"></i> {{ sub_comment.createJalalitime}}
                                                    </li>
                                                    <li>
                                                        <i class="fa fa-calendar"></i> {{ sub_comment.createJalalidate }}
                                                    </li>
                                                </ul>
                                                <p>
                                                    {{ sub_comment.message }}
                                                </p>
                                            </div>
                                        </li>
                                    {% endfor %}
                                {% endfor %}

                            </ul>
                        </div>
                        <!--/Response-area-->
                        <div class="replay-box" id="comment_form">
                            {% if request.user.is_authenticated %}
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h2>نظـر خود را بنویسیـد</h2>
                                        <div class="text-area">
                                            <input type="hidden" value="" id="parent_id" >
                                            <div class="blank-arrow">
                                                <label>متن پیام</label>
                                            </div>
                                            <span>*</span>
                                            <textarea name="message" rows="11" id="commentText"></textarea>
                                            <div class="col-md-12 form-group">
                                            </div>
                                            <a class="btn btn-primary" onclick="sendBrandComments({{ productsbrand.id }})">
                                                ارسـال نظـر</a>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <div class="alert alert-warning">
                                    برای درج نظر می بایست <a href="{% url 'login-page' %}">لاگین</a> کنید
                                </div>
                            {% endif %}
                        </div>
                        <!--/Repaly Box-->
                        </div>
                    {% endif %}
            </div>
        </div>

        </div>
        </div>
    </section>

{% endblock %}

productionsApp/templates/productionsApp/detailsProductions.html
{% extends 'shared/master.html' %}
{% load ratings %}
{% load jalali_tags %}
{% load poll_extras %}
{% load static %}
{% block title %}{{ products.title }}{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12 padding-right">
                    <div class="product-details">
                        <!--product-details-->
                        <div class="col-md-5">
                            <div class="view-product">
                                {% if products.image %}
                                    <img src="{{ products.image.url }}" alt="{{ products.title }}" id="mainImage"/>
                                {% endif %}
                                <h3>بزرگنمایـی</h3>
                            </div>
                            <div id="similar-product" class="carousel slide" data-ride="carousel"><!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    {% for group in product_galleries %}
                                        <div class="item {% if forloop.first %}active{% endif %}">
                                            {% for gallery in group %}
                                                <a onclick="showLargeImage('{{ gallery.image.url }}')">
                                                    <img src="{{ gallery.image.url }}" width="125" height="75" alt="">
                                                </a>
                                            {% endfor %}
                                        </div>
                                    {% endfor %}
                                </div>
                                <!-- Controls -->
                                <a class="right item-control" href="#similar-product" data-slide="next">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                                <a class="left item-control" href="#similar-product" data-slide="prev">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="product-information">
                                <div>
                                    <h2>{{ products.title }}</h2>
                                    <p>شناسـه : {{ products.id }}</p>
                                    <p>بازدید : {{ visit }}</p>
                                </div>
                                <span>
                                    <span>قیمت : {{ products.price | three_digits_currency}} </span>
                                </span>
                                <br>
                                {% if products.productCount == 0 %}
                                    <label disabled style="font-size: x-large">تعداد :   </label>
                                    <p style="color: red;font-size: large">
                                        موجودی این محصول به پایان رسیده است.
                                    </p>
                                    <button class="btn btn-fefault cart disabled">
                                        <i class="fa fa-shopping-cart disabled"></i>
                                        افـزودن به سبـد خریـد
                                    </button>
                                {% else %}
                                    <label active style="font-size: x-large">تعداد :   </label>
                                    <input type="number" size="2" min="1" max="{{ products.productCount }}" id="count" value="1" class="search_box"/>
                                    <button type="button" class="btn btn-fefault cart" onclick="addProductToOrder({{ products.id }}, {{ products.productCount }})">
                                        <i class="fa fa-shopping-cart"></i>
                                        افـزودن به سبـد خریـد
                                    </button>
                                {% endif %}
                            </div>
                            <div>
                                {% if products.brand %}
                                    <p style="font-size: x-large"><b>برنـد :</b> {{ products.brand.title }} </p>
                                {% endif %}
                            </div>
                            <br>
                            <div class="text-warning" style="font-size:small">
                                {% ratings object %}
                            </div>
                        </div>
                    </div><!--/product-information-->
                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#details" data-toggle="tab">جزئیات</a></li>
                                <li><a href="#reviews" data-toggle="tab">نظرات</a></li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="details">
                                <div class="col-md-12" style="font-size:large">
                                    {{ products.Description | safe }}
                                </div>
                            </div>

                            <div class="tab-pane fade" id="reviews">
                                <div class="col-sm-12">
                                    {% if products.haveComments %}
                                        <!--Comments-->
                                        <div class="response-area" id="comments_area">
                                            <h2> نظرات ({{ comments_count }})</h2>
                                            <ul class="media-list">
                                                {% for comment in comments %}
                                                    <li class="media" id="single_comment_box_{{ comment.id }}">
                                                        <a class="pull-right" href="#">
                                                            <img class="media-object" src="/static/images/blog/user.png" alt="">
                                                        </a>
                                                        <div class="media-body">
                                                            <ul class="sinlge-post-meta">
                                                                <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                                                                <li><i class="fa fa-clock-o"></i> {{ comment.createJalalitime }}</li>
                                                                <li>
                                                                    <i class="fa fa-calendar"></i> {{ comment.createJalalidate }}
                                                                </li>
                                                            </ul>
                                                            <p>
                                                                {{ comment.message }}
                                                            </p>
                                                            <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                                                                    class="fa fa-reply"></i>پاسـخ</a>
                                                        </div>
                                                    </li>

                                                    {% for sub_comment in comment.productscomments_set.all %}
                                                        <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                                                            <a class="pull-right" href="#">
                                                                <img class="media-object" src="/static/images/blog/user_response.png" alt="">
                                                            </a>
                                                            <div class="media-body">
                                                                <ul class="sinlge-post-meta">
                                                                    <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                                                                    <li><i class="fa fa-clock-o"></i> {{ sub_comment.createJalalitime}}
                                                                    </li>
                                                                    <li>
                                                                        <i class="fa fa-calendar"></i> {{ sub_comment.createJalalidate }}
                                                                    </li>
                                                                </ul>
                                                                <p>
                                                                    {{ sub_comment.message }}
                                                                </p>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                {% endfor %}

                                            </ul>
                                        </div>
                                        <!--/Response-area-->
                                        <div class="replay-box" id="comment_form">
                                            {% if request.user.is_authenticated %}
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <h2>نظـر خود را بنویسیـد</h2>
                                                        <div class="text-area">
                                                            <input type="hidden" value="" id="parent_id" >
                                                            <div class="blank-arrow">
                                                                <label>متن پیام</label>
                                                            </div>
                                                            <span>*</span>
                                                            <textarea name="message" rows="11" id="commentText"></textarea>
                                                            <div class="col-md-12 form-group">
                                                            </div>
                                                            <a class="btn btn-primary" onclick="sendProductComments({{ products.id }})">
                                                                ارسـال نظـر</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% else %}
                                                <div class="alert alert-warning">
                                                    برای درج نظر می بایست <a href="{% url 'login-page' %}">لاگین</a> کنید
                                                </div>
                                            {% endif %}
                                        </div>
                                        <!--/Repaly Box-->
                                        </div>
                                    {% endif %}
                            </div>
                        </div><!--/category-tab-->

    </section>
{% endblock %}