chatApp/urls.py
from django.urls import path
from chatApp import views

urlpatterns = [

]

productionsApp/api/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from productionsApp.api import views

router = DefaultRouter()
router.register('product-ratings', views.ProductRatingsVS, basename='product-ratings')

urlpatterns = [
    path('', include(router.urls)),
    # Products' Links
    path('products/', views.ProductsVS.as_view(), name='all-production'),
    path('products/gallery/', views.ProductGalleryGL.as_view(), name='product-galleries'),
    path('products/<int:pk>', views.ProductDetailsVS.as_view(), name='brand-detail'),
    path('product-list/', views.ProductList.as_view(), name='product-list-by-price'),
    # Brands' Links
    path('brands/', views.BrandsVS.as_view(), name='all-brands'),
    path('brands/<int:pk>', views.BrandDetailsVS.as_view(), name='brand-detail'),
    path('brands/<brand>', views.BrandFilteringGA.as_view(), name='product-list-by-brand'),
    # Categories' Links
    path('category/', views.CategoryFilteringGA.as_view(), name='product-list-by-brand'),
    # Tags' Links
    path('tag/', views.ProductsTagsVS.as_view(), name='all-tags'),
    path('tag/<int:pk>/',views.ProductsTagDetailsVS.as_view(), name='all-tags'),
    # Product Comments
    path('<int:id>/product-comments/', views.ProductCommentsGV.as_view(), name='product-comments'),
    path('<int:id>/product-comments/<int:pk>/', views.ProductCommentGR.as_view(), name='product-comment'),
    path('<int:id>/product-comments/create/', views.CreateProductCommentGC.as_view(), name='product-comments-create'),
    path('<int:id>/product-comments/change/<int:pk>/', views.ChangeProductCommentGRUD.as_view(),
         name='product-comments-change'),
    # Brand Comments
    path('<int:id>/brand-comments/', views.BrandCommentsGL.as_view(), name='brand-comments'),
    path('<int:id>/brand-comments/<int:pk>/', views.BrandCommentGR.as_view(), name='brand-comment'),
    path('<int:id>/brand-comments/create/', views.CreateBrandCommentGC.as_view(), name='brand-comments-create'),
    path('<int:id>/brand-comments/change/<int:pk>/', views.ChangeBrandCommentGRUD.as_view(),
         name='brand-comments-change'),
]

productionsApp/urls.py
from django.urls import path
from productionsApp import views

urlpatterns = [
    path('', views.AllProductionsView.as_view(), name='all-productions-page'),
    path('add-product-comment/', views.addProductComment, name='product-comment-page'),
    path('add-brand-comment/', views.addBrandComment, name='brand-comment-page'),
    path('brands/', views.BrandsListView.as_view(), name='brands-page'),
    path('brands/<brand>', views.AllProductionsView.as_view(), name='product-list-by-brand'),
    path('category/<cat>', views.AllProductionsView.as_view(), name='product-list-by-category'),
    path('brands/<pk>/', views.BrandDetailView.as_view(), name='brand-detail-page'),
    path('<slug:slug>/', views.ProductionsDetailView.as_view(), name='detail-productions-page'),
]

shopCenter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # URLs
    path('', include('homeApp.urls')),
    path('', include('contactApp.urls')),
    path('', include('userAccountApp.urls')),
    path('userpanel/', include('userPanelApp.urls')),
    path('order/', include('orderApp.urls')),
    path('productions/', include('productionsApp.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('admin/', admin.site.urls),

    # API URLs Version 1
    path('api/v1/', include('homeApp.api.urls')),
    path('api/v1/', include('contactApp.api.urls')),
    path('api/v1/', include('userAccountApp.api.urls')),
    path('api/v1/userpanel/', include('userPanelApp.api.urls')),
    path('api/v1/order/', include('orderApp.api.urls')),
    path('api/v1/productions/', include('productionsApp.api.urls')),
    path('api/v1/ratings/', include('star_ratings.urls', namespace='ratings')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productionsApp/models.py
from django.db import models
from django.shortcuts import reverse
from jalali_date import datetime2jalali, date2jalali
from shopCenter import settings


# Brand Model for Products
class ProductsBrand(models.Model):
    title = models.CharField(max_length=200, db_index=True, verbose_name='نام برند')
    titleEN = models.CharField(max_length=300, db_index=True, verbose_name='نام انگلیسی برند', null=True)
    isActive = models.BooleanField(verbose_name='فعال / غیرفعال')
    image = models.ImageField(upload_to='brands/', null=True, blank=True, verbose_name='تصویر محصول')
    shortDescription = models.TextField(verbose_name='توضیحات کوتاه', null=True)
    description = models.TextField(verbose_name='توضیحات برند', null=True)
    createDate = models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ نوشته')
    haveComments = models.BooleanField(null=True, blank=True, verbose_name='نمایش نظرات')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'برند'
        verbose_name_plural = 'برند ها'

    def createJalalidate(self):
        date = date2jalali(self.createDate).strftime('14%y/%m/%d')
        return date

    def createJalalitime(self):
        time = datetime2jalali(self.createDate).strftime('%H : %M')
        return time


# Comment Model for Brand
class BrandsComments(models.Model):
    isActive = models.BooleanField(verbose_name='نمایش نظر', null=True)
    brand = models.ForeignKey(ProductsBrand, on_delete=models.CASCADE, verbose_name='نام برند')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='نام کاربر')
    parent = models.ForeignKey('BrandsComments', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    createDate = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نظر')
    message = models.TextField(verbose_name='متن نظر')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'نظر درباره برند'
        verbose_name_plural = 'نظرات برند'

    def createJalalidate(self):
        date = date2jalali(self.createDate).strftime('14%y/%m/%d')
        return date

    def createJalalitime(self):
        time = datetime2jalali(self.createDate).strftime('%H:%M')
        return time


# Category Model for Products
class ProductsCategory(models.Model):
    title = models.CharField(max_length=300, db_index=True, verbose_name='عنوان دسته بندی')
    urlTitle = models.CharField(max_length=300, db_index=True, verbose_name='Url عنوان در')
    image = models.ImageField(upload_to='images/category', null=True, blank=True, verbose_name='تصویر دسته بندی')
    isActive = models.BooleanField(verbose_name='فعال / غیرفعال')
    isDelete = models.BooleanField(verbose_name='حذف شده / نشده', null=True)
    parent = models.ForeignKey('CategoryParent', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='دسته بندی والد')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی محصول'
        verbose_name_plural = 'دسته بندی  های محصولات'


# Parent Model for Category
class CategoryParent(models.Model):
    title = models.CharField(max_length=300, db_index=True, verbose_name='نام')
    titleEN = models.CharField(max_length=300, db_index=True, verbose_name='نام انگلیسی', null=True)
    isActive = models.BooleanField(verbose_name='فعال / غیرفعال')

    class Meta:
        verbose_name = 'دسته بندی والد'
        verbose_name_plural = 'دسته بندی های والد'

    def __str__(self):
        return self.title


# Product Model
class Products(models.Model):
    title = models.CharField(max_length=300, verbose_name='نام محصول')
    category = models.ManyToManyField(ProductsCategory, related_name='productCategories',
                                      verbose_name='دسته بندی محصول')
    image = models.ImageField(upload_to='products/', null=True, blank=True, verbose_name='تصویر محصول')
    brand = models.ForeignKey(ProductsBrand, on_delete=models.CASCADE, verbose_name='برند', null=True, blank=True)
    price = models.IntegerField(verbose_name='قیمت')
    productCount = models.IntegerField(verbose_name='تعداد محصول', default=0)
    dateOfCreate = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='تاریخ ثبت')
    shortDescription = models.CharField(max_length=360, db_index=True, default='empty', verbose_name='توضیحات کوتاه')
    Description = models.TextField(db_index=True, verbose_name='توضیحات اصلی')
    isActive = models.BooleanField(default=False, verbose_name='فعال /غیر فعال')
    slug = models.SlugField(default="", null=False, db_index=True, blank=True, max_length=200, unique=True,
                            verbose_name='عنوان در url')
    isDelete = models.BooleanField(verbose_name='حذف شده / نشده')
    haveComments = models.BooleanField(null=True, blank=True, verbose_name='نمایش نظرات')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def get_absolute_url(self):
        return reverse('product-details-page', args=[self.slug])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


# Gallery Model for Products
class ProductGallery(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول',
                                related_name='product_gallery')
    image = models.ImageField(upload_to='images/productGallery', verbose_name='تصویر')

    class Meta:
        verbose_name = 'تصویر محصول'
        verbose_name_plural = 'تصاویر محصولات'

    def __str__(self):
        return self.product.title


# Comment Model for Products
class ProductsComments(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول')
    parent = models.ForeignKey('ProductsComments', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='کاربر', )
    createDate = models.DateTimeField(verbose_name='تاریخ ثبت', auto_now_add=True)
    message = models.TextField(verbose_name='متن نظر')

    class Meta:
        verbose_name = 'نظر درباره محصول'
        verbose_name_plural = 'نظرات محصولات'

    def createJalalidate(self):
        date = date2jalali(self.createDate).strftime('14%y/%m/%d')
        return date

    def createJalalitime(self):
        time = datetime2jalali(self.createDate).strftime('%H:%M')
        return time

    def __str__(self):
        return str(self.user)


# Tag Model for Products
class ProductsTags(models.Model):
    caption = models.CharField(max_length=300, db_index=True, verbose_name='تگ محصول')
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product_tags')

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = 'تگ محصول'
        verbose_name_plural = 'تگ های محصولات'


# Visit Model for Products
class ProductsVisit(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول', related_name='productsvisit')
    ip = models.CharField(max_length=30, verbose_name='آی پی کاربر')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='کاربر', null=True, blank=True,
                             on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.product.title} / {self.ip}'

    class Meta:
        verbose_name = 'بازید محصول'
        verbose_name_plural = 'بازید های محصول'


# Rating Model for Products
class ProductsRating(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name='محصول')
    rating = models.IntegerField(verbose_name='امتیاز', null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='کاربر')
    isRating = models.BooleanField(verbose_name='نظر داده / نداده')

    class Meta:
        verbose_name = 'امتیاز محصول'
        verbose_name_plural = 'امتبازات محصولات'

    def __str__(self):
        return str(self.product)

productionsApp/templates/productionsApp/includes/brandProduct.html
<div class="brands_products">
    <h2>برنـد ها</h2>
    <div class="brands-name">
        <ul class="nav nav-pills nav-stacked">
            {% for brand in productions_brand %}
                <li><a href="{% url 'product-list-by-brand' brand=brand.titleEN %}"> <span class="pull-left">({{ brand.productions_count }})</span>{{ brand.titleEN }}</a></li>
            {% endfor %}

        </ul>
    </div>
</div>

productionsApp/templates/productionsApp/includes/cardProductions.html
{% load poll_extras %}
<div class="col-sm-4">
    <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                <img src="{{ product.image.url }}" alt="" />
                <h2>{{ product.price | three_digits_currency}} </h2>
                <p>{{ product.title }}</p>
                <button type="button" onclick="addProductToOrder({{ product.id }})"  class="btn btn-default add-to-cart">
                    <i class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</button>
            </div>
            <div class="product-overlay">
                <div class="overlay-content">
                    <h2>{{ product.price | three_digits_currency}} </h2>
                    <p>{{ product.title }}</p>
                    <button type="button" onclick="addProductToOrder({{ product }})" class="btn btn-default add-to-cart">
                        <i class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</button>
                </div>
            </div>
        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href="{% url 'detail-productions-page' slug=product.slug %}">
                    <i class="fa fa-plus-square"></i>مشاهده جزئیات</a></li>
            </ul>
        </div>
    </div>
</div>

productionsApp/templates/productionsApp/includes/categoryPartial.html
<div class="panel-group category-products" id="accordian"><!--category-productsr-->
    {% for main_category in main_categories %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    {% if main_category.productscategory_set.all %}
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{ main_category.titleEN }}">
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            {{ main_category.title }}
                        </a>
                    {% else %}
                        <a href="">
                            {{ main_category.title }}
                        </a>
                    {% endif %}

                </h4>
            </div>
            {% if main_category.productscategory_set.all %}
                <div id="{{ main_category.titleEN }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            {% for sub_main_category in main_category.productscategory_set.all %}
                                <li><a href="{% url 'product-list-by-category' cat=sub_main_category.urlTitle %}">{{ sub_main_category }}</a></li>
                            {% endfor %}
                    
                        </ul>
                    </div>
                </div>

            {% endif %}
        </div>
    {% endfor %}

productionsApp/templates/productionsApp/includes/commentsBrand.html
{% load jalali_tags  %}

<h2> نظرات ({{ commentCount }})</h2>
<ul class="media-list">
    {% for comment in comments %}
        <li class="media" id="single_comment_box_{{ comment.id }}">
            <a class="pull-right" href="#">
                <img class="media-object" src="/static/images/blog/user.png" alt="">
            </a>
            <div class="media-body">
                <ul class="sinlge-post-meta">
                    <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                    <li><i class="fa fa-clock-o"></i> {{ comment.createJalalitime }}</li>
                    <li>
                        <i class="fa fa-calendar"></i> {{ comment.createJalalidate }}
                    </li>
                </ul>
                <p>
                    {{ comment.text }}
                </p>
                <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                        class="fa fa-reply"></i>پاسـخ</a>
            </div>
        </li>

        {% for sub_comment in comment.brandscomments_set.all %}
            <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                <a class="pull-right" href="#">
                    <img class="media-object" src="/static/images/blog/user_response.png" alt="">
                </a>
                <div class="media-body">
                    <ul class="sinlge-post-meta">
                        <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                        <li><i class="fa fa-clock-o"></i> {{ sub_comment.createJalalitime }}
                        </li>
                        <li>
                            <i class="fa fa-calendar"></i> {{ sub_comment.createJalalidate }}
                        </li>
                    </ul>
                    <p>
                        {{ sub_comment.text }}
                    </p>
                </div>
            </li>
        {% endfor %}
    {% endfor %}

</ul>

productionsApp/templates/productionsApp/includes/commentsProduction.html
{% load jalali_tags  %}

<h2> نظرات ({{ commentCount }})</h2>
<ul class="media-list">
    {% for comment in comments %}
        <li class="media" id="single_comment_box_{{ comment.id }}">
            <a class="pull-right" href="#">
                <img class="media-object" src="/static/images/blog/user.png" alt="">
            </a>
            <div class="media-body">
                <ul class="sinlge-post-meta">
                    <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                    <li><i class="fa fa-clock-o"></i> {{ comment.createJalalitime }}</li>
                    <li>
                        <i class="fa fa-calendar"></i> {{ comment.createJalalidate }}
                    </li>
                </ul>
                <p>
                    {{ comment.text }}
                </p>
                <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                        class="fa fa-reply"></i>پاسـخ</a>
            </div>
        </li>

        {% for sub_comment in comment.articlecomment_set.all %}
            <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                <a class="pull-right" href="#">
                    <img class="media-object" src="/static/images/blog/user_response.png" alt="">
                </a>
                <div class="media-body">
                    <ul class="sinlge-post-meta">
                        <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                        <li><i class="fa fa-clock-o"></i> {{ sub_comment.create_date | time }}
                        </li>
                        <li>
                            <i class="fa fa-calendar"></i> {{ sub_comment.create_date|show_jalali_date }}
                        </li>
                    </ul>
                    <p>
                        {{ sub_comment.text }}
                    </p>
                </div>
            </li>
        {% endfor %}
    {% endfor %}

</ul>

productionsApp/templates/productionsApp/includes/productRating.html
 {% if not user.is_authorized %}
    <span class="fa fa-star cursore-pointer"></span>
    <span class="fa fa-star cursore-pointer"></span>
    <span class="fa fa-star cursore-pointer"></span>
    <span class="fa fa-star cursore-pointer"></span>
    <span class="fa fa-star cursore-pointer" id="star-five" onclick="addRating({{  }})"></span>
{% endif %}

{% load jalali_tags  %}

<h2> نظرات ({{ commentCount }})</h2>
<ul class="media-list">
    {% for comment in comments %}
        <li class="media" id="single_comment_box_{{ comment.id }}">
            <a class="pull-right" href="#">
                <img class="media-object" src="/static/images/blog/user.png" alt="">
            </a>
            <div class="media-body">
                <ul class="sinlge-post-meta">
                    <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                    <li><i class="fa fa-clock-o"></i> {{ comment.createJalalitime }}</li>
                    <li>
                        <i class="fa fa-calendar"></i> {{ comment.createJalalidate }}
                    </li>
                </ul>
                <p>
                    {{ comment.text }}
                </p>
                <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                        class="fa fa-reply"></i>پاسـخ</a>
            </div>
        </li>

        {% for sub_comment in comment.brandscomments_set.all %}
            <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                <a class="pull-right" href="#">
                    <img class="media-object" src="/static/images/blog/user_response.png" alt="">
                </a>
                <div class="media-body">
                    <ul class="sinlge-post-meta">
                        <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                        <li><i class="fa fa-clock-o"></i> {{ sub_comment.createJalalitime }}
                        </li>
                        <li>
                            <i class="fa fa-calendar"></i> {{ sub_comment.createJalalidate }}
                        </li>
                    </ul>
                    <p>
                        {{ sub_comment.text }}
                    </p>
                </div>
            </li>
        {% endfor %}
    {% endfor %}

</ul>